Ensure the job is failed for PR merge failure
* Release chart if merge is a success
* Prevent draft PRs from running workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,6 +8,7 @@ jobs:
   chart-certification:
     name: Chart Certification
     runs-on: ubuntu-20.04
+    if: ${{ github.event.pull_request.draft == false }}
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -27,7 +28,7 @@ jobs:
           ./ve1/bin/sanity-check-pr --api-url=${{ github.event.pull_request._links.self.href }}
 
       - uses: actions/github-script@v3
-        if: ${{ steps.sanity_check_pr_content.outcome == 'success'}}
+        if: ${{ steps.sanity_check_pr_content.outcome == 'success' }}
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
@@ -40,7 +41,7 @@ jobs:
             })
 
       - uses: actions/github-script@v3
-        if: ${{ steps.sanity_check_pr_content.outcome == 'failure'}}
+        if: ${{ steps.sanity_check_pr_content.outcome == 'failure' }}
         continue-on-error: true
         with:
           github-token: ${{secrets.GITHUB_TOKEN}}
@@ -53,7 +54,7 @@ jobs:
             })
 
       - name: Reflect on Sanity Check PR Content
-        if: ${{ steps.sanity_check_pr_content.outcome == 'failure'}}
+        if: ${{ steps.sanity_check_pr_content.outcome == 'failure' }}
         run: |
           echo "The 'Sanity Check PR Content' step has failed."
           exit 1
@@ -159,7 +160,7 @@ jobs:
             });
 
       - name: 'Add label to PR'
-        if: ${{ always() && steps.sanity_check_pr_content.outcome == 'success'}}
+        if: ${{ always() && steps.sanity_check_pr_content.outcome == 'success' }}
         uses: actions/github-script@v3
         with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
@@ -173,7 +174,7 @@ jobs:
                 issue_number: Number(issue_number),
                 owner: context.repo.owner,
                 repo: context.repo.repo,
-                labels: ['authorized-request']
+                labels: ['authorized-request', 'automerge']
             })};
 
       - name: 'Approve PR'
@@ -190,7 +191,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           MERGE_METHOD: squash
-          MERGE_LABELS: ""
+          MERGE_LABELS: "automerge,!hold"
+          MERGE_REMOVE_LABELS: "automerge"
 
       - name: Block until there is no running workflow
         uses: softprops/turnstyle@v1
@@ -203,6 +205,7 @@ jobs:
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
       - name: Release Charts
+        if: ${{ !contains(github.event.pull_request.labels.*.names, 'automerge') }}
         env:
           GITHUB_REF: ${{ github.ref }}
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
@@ -217,6 +220,7 @@ jobs:
           ../ve1/bin/chart-repo-manager --repository=${{ github.repository }} --index-branch=${INDEX_BRANCH} --api-url=${{ github.event.pull_request._links.self.href }} --pr-number=${{ github.event.number }}
 
       - name: Release
+        if: ${{ !contains(github.event.pull_request.labels.*.names, 'automerge') }}
         uses: softprops/action-gh-release@master
         continue-on-error: true
         with:
@@ -225,3 +229,9 @@ jobs:
           fail_on_unmatched_files: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Error PR merge failure
+        if: ${{ contains(github.event.pull_request.labels.*.names, 'automerge') }}
+        run: |
+          echo "Pull request failed to merge."
+          exit 1
