Ensure the job is failed for PR merge failure
* Release chart if merge is a success
* Prevent draft PRs from running workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,6 +8,7 @@ jobs:
   chart-certification:
     name: Chart Certification
     runs-on: ubuntu-20.04
+    if: github.event.pull_request.draft == false
     steps:
       - name: Checkout
         uses: actions/checkout@v2
@@ -173,7 +174,7 @@ jobs:
                 issue_number: Number(issue_number),
                 owner: context.repo.owner,
                 repo: context.repo.repo,
-                labels: ['authorized-request']
+                labels: ['authorized-request', 'automerge']
             })};
 
       - name: 'Approve PR'
@@ -190,7 +191,8 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           MERGE_METHOD: squash
-          MERGE_LABELS: ""
+          MERGE_LABELS: "automerge,!hold"
+          MERGE_REMOVE_LABELS: "automerge"
 
       - name: Block until there is no running workflow
         uses: softprops/turnstyle@v1
@@ -203,6 +205,7 @@ jobs:
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
 
       - name: Release Charts
+        if: "!contains(github.event.pull_request.labels.*.name, 'automerge')"
         env:
           GITHUB_REF: ${{ github.ref }}
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
@@ -217,6 +220,7 @@ jobs:
           ../ve1/bin/chart-repo-manager --repository=${{ github.repository }} --index-branch=${INDEX_BRANCH} --api-url=${{ github.event.pull_request._links.self.href }} --pr-number=${{ github.event.number }}
 
       - name: Release
+        if: "!contains(github.event.pull_request.labels.*.name, 'automerge')"
         uses: softprops/action-gh-release@master
         continue-on-error: true
         with:
@@ -225,3 +229,9 @@ jobs:
           fail_on_unmatched_files: true
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Error PR merge failure
+        if: "contains(github.event.pull_request.labels.*.name, 'automerge')"
+        run: |
+          echo "Pull request failed to merge."
+          exit 1
